name: example
description: An example for flame_3d. The example shows how to set up 3D support in a flame game.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame: ^1.14.0
  flame_3d:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
