name: flame_devtools_example
description: Simple Flame example used to help the development of the devtools extension.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flame: ^1.13.1
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.1.2
  flutter_test:
    sdk: flutter
